// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/pod.proto

package pod

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PodService service

func NewPodServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PodService service

type PodService interface {
	AddPod(ctx context.Context, in *PodInfo, opts ...client.CallOption) (*Response, error)
	DeletePod(ctx context.Context, in *PodID, opts ...client.CallOption) (*Response, error)
	FindPodByID(ctx context.Context, in *PodID, opts ...client.CallOption) (*PodInfo, error)
	UpdatePod(ctx context.Context, in *PodInfo, opts ...client.CallOption) (*Response, error)
	FindPodAll(ctx context.Context, in *FindAll, opts ...client.CallOption) (*PodInfos, error)
}

type podService struct {
	c    client.Client
	name string
}

func NewPodService(name string, c client.Client) PodService {
	return &podService{
		c:    c,
		name: name,
	}
}

func (c *podService) AddPod(ctx context.Context, in *PodInfo, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PodService.AddPod", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podService) DeletePod(ctx context.Context, in *PodID, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PodService.DeletePod", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podService) FindPodByID(ctx context.Context, in *PodID, opts ...client.CallOption) (*PodInfo, error) {
	req := c.c.NewRequest(c.name, "PodService.FindPodByID", in)
	out := new(PodInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podService) UpdatePod(ctx context.Context, in *PodInfo, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PodService.UpdatePod", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podService) FindPodAll(ctx context.Context, in *FindAll, opts ...client.CallOption) (*PodInfos, error) {
	req := c.c.NewRequest(c.name, "PodService.FindPodAll", in)
	out := new(PodInfos)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PodService service

type PodServiceHandler interface {
	AddPod(context.Context, *PodInfo, *Response) error
	DeletePod(context.Context, *PodID, *Response) error
	FindPodByID(context.Context, *PodID, *PodInfo) error
	UpdatePod(context.Context, *PodInfo, *Response) error
	FindPodAll(context.Context, *FindAll, *PodInfos) error
}

func RegisterPodServiceHandler(s server.Server, hdlr PodServiceHandler, opts ...server.HandlerOption) error {
	type podService interface {
		AddPod(ctx context.Context, in *PodInfo, out *Response) error
		DeletePod(ctx context.Context, in *PodID, out *Response) error
		FindPodByID(ctx context.Context, in *PodID, out *PodInfo) error
		UpdatePod(ctx context.Context, in *PodInfo, out *Response) error
		FindPodAll(ctx context.Context, in *FindAll, out *PodInfos) error
	}
	type PodService struct {
		podService
	}
	h := &podServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PodService{h}, opts...))
}

type podServiceHandler struct {
	PodServiceHandler
}

func (h *podServiceHandler) AddPod(ctx context.Context, in *PodInfo, out *Response) error {
	return h.PodServiceHandler.AddPod(ctx, in, out)
}

func (h *podServiceHandler) DeletePod(ctx context.Context, in *PodID, out *Response) error {
	return h.PodServiceHandler.DeletePod(ctx, in, out)
}

func (h *podServiceHandler) FindPodByID(ctx context.Context, in *PodID, out *PodInfo) error {
	return h.PodServiceHandler.FindPodByID(ctx, in, out)
}

func (h *podServiceHandler) UpdatePod(ctx context.Context, in *PodInfo, out *Response) error {
	return h.PodServiceHandler.UpdatePod(ctx, in, out)
}

func (h *podServiceHandler) FindPodAll(ctx context.Context, in *FindAll, out *PodInfos) error {
	return h.PodServiceHandler.FindPodAll(ctx, in, out)
}
